<html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<body>			
	<!-- <form method="POST" action="ajax_VNairlines.php"> -->
	<!-- <form method="POST" action="ajax_vietjetair.php"> -->
	<?php echo $this->tag->form("search/searchflight"); ?>
		<input type="text" name="loaive" id="loaive" value="">
		<input type="text" name="RoundTrip" id="RoundTrip" value="0">
		<input type="text" name="Origin1" id="Origin1" value="SGN">
		<input type="text" name="Destination1" id="Destination1" value="HAN">
		<input type="text" name="_time1" id="_time1" value="30/07/2016">
		<input type="text" name="_time2" id="_time2" value="22/08/2016">
		<input type="text" name="FindMonth" id="FindMonth" value="0">
		<input type="text" name="pass" id="pass" value="123123123">		
		<input type="submit" />
	</form>
	
</body>

</html>